### ISSUE TITLE
Chrome compatibility

### ISSUE THREAD

**Issue by mauvaisetroupe** [mauvaisetroupe/ea-design-it#115]
2023-09-23 07:21:54.589  WARN 27175 --- [esign-it-task-1] t.j.c.liquibase.AsyncSpringLiquibase     : Starting Liquibase asynchronously, your database might not be ready at startup!
2023-09-23 07:22:17.102 ERROR 27175 --- [  XNIO-1 task-1] c.m.eadesignit.web.rest.AccountResource  : Exception in getAccount() with cause = 'NULL' and exception = 'User could not be found'

com.mauvaisetroupe.eadesignit.web.rest.AccountResource$AccountResourceException: User could not be found
	at com.mauvaisetroupe.eadesignit.web.rest.AccountResource.lambda$1(AccountResource.java:106)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at com.mauvaisetroupe.eadesignit.web.rest.AccountResource.getAccount(AccountResource.java:106)
	at com.mauvaisetroupe.eadesignit.web.rest.AccountResource$$FastClassBySpringCGLIB$$68ac9ab.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)

**Comment by mauvaisetroupe** [comment]
No pb
